project:
  type: website
  output-dir: ../docs

website:
  title: "Talks about incentivizing open science"
  navbar:
    left:
      - href: https://github.com/poldrack/talks-IncentivingGoodScience
        text: Github page

format:
  html:
    theme: flatly
    css: styles.css

